//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilaFattakhova321_Pets.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int Id_pet { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_type { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Pet_type Pet_type { get; set; }
    }
}
